### ISSUE TITLE
Doesn't work with 0.9 gateway

### ISSUE THREAD

**Issue by gorbunovav** [mozilla-iot/wake-on-lan-adapter#4]
Docker container with the gateway starts to eat RAM upon add-on installation, it stops if you disable the add-on.

#### Environment:

Raspberry Pi 4
Raspbian 10
Docker version 19.03.1, build 74b1e89
Image: mozillaiot/gateway:0.9.2-arm

#### docker-compose.yml:

```
version: "3"

services:
  webthings-gateway:
    container_name: webthings-gateway
    image: mozillaiot/gateway:arm
    restart: unless-stopped
    network_mode: host
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - ./data:/home/node/.mozilla-iot
```
